### ISSUE TITLE
Empty string parsing

### ISSUE THREAD

**Issue by kylesferrazza** [SamedhG/sorer#3]
Seems like extra double quotes are printed when an empty string is read:

```
$ echo '<"">' > in.sor
$ ./sorer -f in.sor -from 0 -len 4 -print_col_idx 0 0
""""
```

**Comment by SamedhG** [comment]
Thanks for the bug report will look into fixing it

**Comment by SamedhG** [comment]
We have fixed this bug and added a test case to check it.
